config/routes.rb
Rails.application.routes.draw do


  resources :labels, only: [:show]
  resources :questions
  resources :advertisements
  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end
  resources :users, only: [:new, :create, :show]
  post 'users/confirm' => 'users#confirm'

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :sessions, only: [:new, :create, :destroy]
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, except: [:edit, :new]
      end
    end
  end
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'faq' => 'welcome#faq'

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  default_scope { order('updated_at ASC')}

  after_create :send_favorite_emails

  private

  def send_favorite_emails
    post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end
end

app/models/commenting.rb
class Commenting < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label <ActiveRecord::Base
  has_many :labelings
  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
    return Label.none if label_string.blank?
    label_string.split(',').map do |label|
      Label.find_or_create_by(name: label.strip)
    end
  end
end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  belongs_to :label
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topic.public' => true) }

  validates :title, length: { minimum: 5}, presence: true
  validates :body, length: { minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic

  validates :title, length: { minimum: 3 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :price, presence: true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :sponsored_posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :visible_to, -> (user) { user ? all : publicly_viewable}
  scope :publicly_viewable, -> { where(public: true)}
  scope :privately_viewable, -> {where(public: false)}

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true
  # validates :public, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase }
  before_save :format_name
  before_save { self.role ||= :member }

  before_create :generate_auth_token

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, if: 'password_digest.nil?'
  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 254 }

  has_secure_password

  enum role: [:member, :admin]

  def format_name
    self.name = name.split.map { |name| name.capitalize }.join(' ') if name
  end

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def generate_auth_token
    loop do
      self.auth_token = SecureRandom.base64(64)
      break unless User.find_by(auth_token: auth_token)
    end
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private
  def update_post
    post.update_rank
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create( question_params )

    if @question.save
      flash[:notice] = 'Your Question has been saved.'
      redirect_to @question
    else
      flash.now[:alert] = 'There was a problem saving your question. Please ask again.'
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.update_attributes( question_params )

    if @question.save
      flash[:notice] = 'Question was updated'
      redirect_to @question
    else
      flash.now[:alert] = 'There was an error updating your question. Please try again.'
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      flash[:notice] = "'#{@question.title}' has been removed."
      redirect_to questions_path
    else
      flash.now[:alert] = 'We had trouble deleting your question. Please try again.'
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :resolved)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
    current_user && (current_user == comment.user || current_user.admin?)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
  def labels_to_buttons(labels)
    raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end

  def user_is_authorized_to_edit?(post)
    current_user && (current_user == post.user || current_user.moderator? || current_user.admin?)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
  def user_is_authorized_to_update_topic?
    current_user && (current_user.admin? || current_user.moderator?)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/questions/edit.html.erb
<div class="row">
  <h1>Edit Your Question</h1>
  <p>Please modify your question, remembering to keep a respectful tone</p>

  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title %>

        <%= f.label :body %>
        <%= f.text_field :body %>

        <%= f.label :resolved %>
        <%= f.check_box :resolved %>
      </div>

      <div class="form-field">
        <%= f.submit 'Save', class: 'btn btn-success' %>
        <%= link_to 'Cancel', @question, class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<p>These are the questions posted</p>
<div class="container">
  <ul class="nav nav-tabs">
    <li class="pull-right"><%= link_to 'Ask a Question', new_question_path, class: 'btn btn-primary' %></li>
  </ul>
</div>

<% @questions.each do |question| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to question.title, question %>
      </h4>
    </div>
  </div>
<% end %>

app/views/questions/new.html.erb
<div class="row">
  <h1>New Questions</h1>
  <p>Please ask relevant questions with a respectful tone</p>

  <div class="col-md-8">
    <%= form_for @question do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter a question...' %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter a body...' %>
      </div>
      <div class="form-group">
        <%= f.label :resolved %>
        <%= f.check_box :resolved %>
      </div>

      <div class="form-field">
        <%= f.submit 'Save', class: 'btn btn-success' %>
        <%= link_to 'Cancel', questions_path, class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<h4>Question is <%= @question.resolved ? 'Resolved' : 'Unresolved' %></h4>
<p><%= @question.body %></p>


<div class="container">
  <div class="nav nav-tabs">
    <%= link_to 'Back to Questions', questions_path %>
    <%= link_to 'Delete Question', @question, method: :delete, class: 'pull-right btn btn-danger', data: {confirm: 'Are you certain you\'d like to delete this question?'} %>
    <%= link_to 'Edit', edit_question_path, class: 'btn btn-info pull-right' %>
  </div>
</div>