config/routes.rb
Rails.application.routes.draw do


  resources :labels, only: [:show]
  resources :questions
  resources :advertisements
  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end
  resources :users, only: [:new, :create, :show]
  post 'users/confirm' => 'users#confirm'

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :sessions, only: [:new, :create, :destroy]
  root 'welcome#index'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show, :create, :update]
      resources :topics, except: [:edit, :new] do
        resources :posts, except: [:edit, :new]
      end
    end
  end
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'faq' => 'welcome#faq'

end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  default_scope { order('updated_at ASC')}

  after_create :send_favorite_emails

  private

  def send_favorite_emails
    post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end
end

app/models/commenting.rb
class Commenting < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/label.rb
class Label <ActiveRecord::Base
  has_many :labelings
  has_many :topics, through: :labelings, source: :labelable, source_type: :Topic
  has_many :posts, through: :labelings, source: :labelable, source_type: :Post

  def self.update_labels(label_string)
    return Label.none if label_string.blank?
    label_string.split(',').map do |label|
      Label.find_or_create_by(name: label.strip)
    end
  end
end

app/models/labeling.rb
class Labeling < ActiveRecord::Base
  belongs_to :labelable, polymorphic: true
  belongs_to :label
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings
  has_many :favorites, dependent: :destroy

  default_scope { order('rank DESC') }
  scope :visible_to, -> (user) { user ? all : joins(:topic).where('topic.public' => true) }

  validates :title, length: { minimum: 5}, presence: true
  validates :body, length: { minimum: 20}, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
  belongs_to :topic

  validates :title, length: { minimum: 3 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :price, presence: true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :sponsored_posts, dependent: :destroy
  has_many :labelings, as: :labelable
  has_many :labels, through: :labelings

  scope :visible_to, -> (user) { user ? all : publicly_viewable}
  scope :publicly_viewable, -> { where(public: true)}
  scope :privately_viewable, -> {where(public: false)}

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true
  # validates :public, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase }
  before_save :format_name
  before_save { self.role ||= :member }

  before_create :generate_auth_token

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true
  validates :password, presence: true, length: { minimum: 6 }, if: 'password_digest.nil?'
  validates :password, length: { minimum: 6 }, allow_blank: true

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 254 }

  has_secure_password

  enum role: [:member, :admin]

  def format_name
    self.name = name.split.map { |name| name.capitalize }.join(' ') if name
  end

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def generate_auth_token
    loop do
      self.auth_token = SecureRandom.base64(64)
      break unless User.find_by(auth_token: auth_token)
    end
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }, presence: true

  private
  def update_post
    post.update_rank
  end
end

app/controllers/sponsored_posts_controller.rb
class SponsoredPostsController < ApplicationController
  def show
    @sponsored_post = SponsoredPost.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @sponsored_post = SponsoredPost.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @sponsored_post = @topic.sponsored_posts.build( sponsored_params )

    if @sponsored_post.save
      flash[:notice] = 'SponsoredPost was saved.'
      redirect_to [@topic, @sponsored_post]
    else
      flash.now[:alert] = 'There was an error saving the Sponsored Post. Please try again.'
      render :new
    end
  end

  def edit
    @sponsored_post = SponsoredPost.find(params[:id])
  end

  def update
    @sponsored_post = SponsoredPost.find(params[:id])
    @sponsored_post.update_attributes( sponsored_params )

    if @sponsored_post.save
      flash[:notice] = 'Sponsored Post was saved.'
      redirect_to [@sponsored_post.topic, @sponsored_post]
    else
      flash.now[:alert] = 'There was an error saving the Sponsored Post. Please try again.'
      render :edit
    end
  end

  def destroy
    @sponsored_post = SponsoredPost.find(params[:id])

    if @sponsored_post.destroy
      flash[:notice] = "'#{@sponsored_post.title}' successfully destroyed"
      redirect_to @sponsored_post.topic
    else
      flash[:alert] = 'There was an error destroying your sponsored post'
      render :show
    end
  end

  private
  def sponsored_params
    params.require(:sponsored_post).permit(:title, :body, :price)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment?(comment)
    current_user && (current_user == comment.user || current_user.admin?)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
  def labels_to_buttons(labels)
    raw labels.map { |l| link_to l.name, label_path(id: l.id), class: 'btn-xs btn-primary' }.join(' ')
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end

  def user_is_authorized_to_edit?(post)
    current_user && (current_user == post.user || current_user.moderator? || current_user.admin?)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def create_session(user)
    session[:user_id] = user.id
  end

  def destroy_session(user)
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/sponsored_posts_helper.rb
module SponsoredPostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
  def user_is_authorized_to_update_topic?
    current_user && (current_user.admin? || current_user.moderator?)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/sponsored_posts/_form.html.erb
<%= form_for [topic, sponsored_post] do |f| %>
  <% if sponsored_post.errors.any? %>
    <div class="alert alert-danger">
      <h4><%= pluralize(sponsored_post.errors.count, 'error') %></h4>
      <ul>
        <% sponsored_post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(sponsored_post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: 'Title your sponsored post' %>
  <% end %>
  <%= form_group_tag(sponsored_post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter your body...' %>
  <% end %>
  <%= form_group_tag(sponsored_post.errors[:price]) do %>
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control' %>
  <% end %>
  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-success' %>
    <%= link_to 'Cancel', topic, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/sponsored_posts/edit.html.erb
<h1>Edit Sponsored Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for sponsored_posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>Hashtags are discouraged.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @sponsored_post.topic, sponsored_post: @sponsored_post } %>
  </div>
</div>

app/views/sponsored_posts/new.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Sponsored Posts Etiquette</p>
    <ul>
      <li>Make sure it rhymes</li>
      <li>Don't use the letter 'A'</li>
      <li>Use of Hashtags strictly forbidden</li>
    </ul>
  </div>

  <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @topic, sponsored_post: @sponsored_post } %>
  </div>
</div>

app/views/sponsored_posts/show.html.erb
<h1><%= @sponsored_post.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @sponsored_post.body %></p>
  </div>
  <div class="col-md-4">
    <ul class="nav nav-tabs">
      <li><%= link_to 'Edit', edit_topic_sponsored_post_path(@sponsored_post.topic, @sponsored_post), class: 'btn btn-success' %></li>

      <li><%= link_to 'Back to Topic', @sponsored_post.topic, class: 'pull-right' %></li>
      <li><%= link_to 'Delete Sponsored Post', [@sponsored_post.topic, @sponsored_post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %></li>
    </ul>
  </div>
</div>